print("what's your name?")
n = input(str())
#print("Hello", n, "How are you ?")
print("Where are you in?")
p = input(str())
print("Hello", n, "How is the weather in", p, "?")
print("what's your age?")
a = input(int())
print("Good to know you are", a, "years old")